# Identifying special matrices
## Instructions
In this assignment, you shall write a function that will test if a 4×4 matrix is singular, i.e. to determine if an inverse exists, before calculating it.

You shall use the method of converting a matrix to echelon form, and testing if this fails by leaving zeros that can’t be removed on the leading diagonal.

Don't worry if you've not coded before, a framework for the function has already been written.
Look through the code, and you'll be instructed where to make changes.
We'll do the first two rows, and you can use this as a guide to do the last two.

### Matrices in Python
In the *numpy* package in Python, matrices are indexed using zero for the top-most column and left-most row.
I.e., the matrix structure looks like this:
```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```
You can access the value of each element individually using,
```python
A[n, m]
```
which will give the n'th row and m'th column (starting with zero).
You can also access a whole row at a time using,
```python
A[n]
```
Which you will see will be useful when calculating linear combinations of rows.

A final note - Python is sensitive to indentation.
All the code you should complete will be at the same level of indentation as the instruction comment.

### How to submit
Edit the code in the cell below to complete the assignment.
Once you are finished and happy with it, press the *Submit Assignment* button at the top of this notebook.

Please don't change any of the function names, as these will be checked by the grading script.

If you have further questions about submissions or programming assignments, here is a [list](https://www.coursera.org/learn/linear-algebra-machine-learning/discussions/weeks/1/threads/jB4klkn5EeibtBIQyzFmQg) of Q&A. You can also raise an issue on the discussion forum. Good luck!

In [7]:
import numpy as np

class MatrixIsSingular(Exception): pass

# Fix row 0: Set the first element to 1, and adjust lower rows
def fixRowZero(A):
    if A[0, 0] == 0:
        A[0] = A[0] + A[1]
    if A[0, 0] == 0:
        A[0] = A[0] + A[2]
    if A[0, 0] == 0:
        A[0] = A[0] + A[3]
    if A[0, 0] == 0:
        raise MatrixIsSingular()
    A[0] = A[0] / A[0, 0]
    return A

# Fix row 1: Set the sub-diagonal element to 0, and set the diagonal element to 1
def fixRowOne(A):
    A[1] = A[1] - A[1, 0] * A[0]  # Eliminate sub-diagonal element
    if A[1, 1] == 0:
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1, 0] * A[0]  # Re-eliminate sub-diagonal
    if A[1, 1] == 0:
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1, 0] * A[0]
    if A[1, 1] == 0:
        raise MatrixIsSingular()
    A[1] = A[1] / A[1, 1]  # Set diagonal element to 1
    return A

# Fix row 2: Set the sub-diagonal elements to zero
def fixRowTwo(A):
    A[2] = A[2] - A[2, 0] * A[0]  # Eliminate the sub-diagonal element in the first column
    A[2] = A[2] - A[2, 1] * A[1]  # Eliminate the sub-diagonal element in the second column
    
    if A[2, 2] == 0:
        A[2] = A[2] + A[3]  # Add the lower row if diagonal element is zero
        A[2] = A[2] - A[2, 0] * A[0]  # Re-eliminate the sub-diagonal element in the first column
        A[2] = A[2] - A[2, 1] * A[1]  # Re-eliminate the sub-diagonal element in the second column

    if A[2, 2] == 0:
        raise MatrixIsSingular()
    
    A[2] = A[2] / A[2, 2]  # Set diagonal element to 1
    return A

# Fix row 3: Set the sub-diagonal elements to zero
def fixRowThree(A):
    A[3] = A[3] - A[3, 0] * A[0]  # Eliminate sub-diagonal element in the first column
    A[3] = A[3] - A[3, 1] * A[1]  # Eliminate sub-diagonal element in the second column
    A[3] = A[3] - A[3, 2] * A[2]  # Eliminate sub-diagonal element in the third column

    if A[3, 3] == 0:
        raise MatrixIsSingular()

    A[3] = A[3] / A[3, 3]  # Set diagonal element to 1
    return A

# Check if the matrix is singular
def isSingular(A):
    B = np.array(A, dtype=np.float_)  # Make a copy of A to work with
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

# Example usage:
A = np.array([[1, 3, 2, 4],
              [2, 6, 5, 8],
              [4, 9, 11, 14],
              [2, 5, 7, 10]], dtype=float)

print(isSingular(A))  # Will return True or False depending on whether the matrix is singular


False


## Test your code before submission
To test the code you've written above, run the cell (select the cell above, then press the play button [ ▶| ] or press shift-enter).
You can then use the code below to test out your function.
You don't need to submit this cell; you can edit and run it as much as you like.

Try out your code on tricky test cases!

In [8]:
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
isSingular(A)

True

In [9]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)
fixRowZero(A)

array([[ 1. ,  7.5, -2.5,  3.5],
       [ 2. ,  8. ,  0. ,  4. ],
       [ 3. , 12. ,  0. ,  5. ],
       [ 1. ,  3. ,  1. ,  3. ]])

In [10]:
fixRowOne(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 3.        , 12.        ,  0.        ,  5.        ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [11]:
fixRowTwo(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [12]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])